name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: sqlite

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Check
      run: make check
      working-directory: ${{ env.WORKING_DIR }}

    - name: Format
      run: make format
      working-directory: ${{ env.WORKING_DIR }}

    - name: Test
      run: make test
      working-directory: ${{ env.WORKING_DIR }}

    - name: Release
      run: make release
      working-directory: ${{ env.WORKING_DIR }}

    # Upload the binary file as an artifact
    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-binary
        path: ${{ env.WORKING_DIR }}/target/release/sqlite # Pointing to the correct binary location